CREATE TABLE IF NOT EXISTS "bf_v10"."user_coupons" (
  "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "user_id" text NOT NULL REFERENCES "bf_v10"."user"("id") ON DELETE CASCADE,
  "code" text NOT NULL,
  "label" text NOT NULL,
  "discount" integer NOT NULL,
  "status" text NOT NULL DEFAULT 'active',
  "earned_from" text NOT NULL,
  "earned_at" timestamp with time zone NOT NULL,
  "used_at" timestamp with time zone,
  "used_order_id" integer REFERENCES "bf_v10"."orders"("id")
);
